using UnityEngine;

public class LaserTrigger : MonoBehaviour
{
    private HudManager hudManager; // âœ… RÃ©fÃ©rence au HUD
    private LaserManager laserManager; // âœ… RÃ©fÃ©rence au HUD

    void Start()
    {
        hudManager = FindObjectOfType<HudManager>(); // ğŸ” Trouve le HUD dans la scÃ¨ne
        laserManager = FindObjectOfType<LaserManager>(); // ğŸ” Trouve le HUD dans la scÃ¨ne
    }



    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player") && !laserManager.IsAlarmActive())
        {
            laserManager.activateAlarm();
        }
    }

    
}
